### ISSUE TITLE
Сделать функцию поиска по фурнитуре

### ISSUE THREAD

**Issue by MaksimTitenko** [LizaMetla/furniture_store#1]
В данную функцию, в параметрах, мы должны передать id поля, по которому будем искать запись в нашей "базе данных". Прим. `def furniture_get(id): pass`.
В этой функции мы должны достать все данные из нашей базы `furnitures = get_from_db_furniture(),` затем в цикле ` for furniture in furnitures: pass` обращаться к каждому furniture['id_furniture'], проверять в if, равен ли он нашему id, если равен, тогда мы возвращаем из функции `furniture`

**Comment by MaksimTitenko** [comment]
Когда выполнишь - нажмёшь close issue ;)

**Comment by LizaMetla** [comment]
As I understand.... Впараметрах я должна перечислять все виды id, чтобы проверить , существуют ли они в нашей базе данных? Прим: def furniture_get(id_furniture, id_department, id_batch, id_product): ? Или же нужно создать 'общую' id в которой будут храниться все id(что я выше перечисляла) ? //So sorry for my easy questions
