### ISSUE TITLE
Разобраться с функцией filter

### ISSUE THREAD

**Issue by MaksimTitenko** [LizaMetla/furniture_store#2]
Данная функция принимает на вход любой список словарей и уменьшает количество словарей в нём с увеличением параметров в функции filter. Пример ниже.
![image](https://user-images.githubusercontent.com/38699903/53881195-106ba080-4024-11e9-93e5-0f0a5d82604d.png)

**Comment by LizaMetla** [comment]
По сути, можно отнести функцию filter() к операции "удаления элемента" ?

**Comment by MaksimTitenko** [comment]
Не совсем. Это функция именно фильтрует данные, но не удаляет их из наше базы данных. Для примера представь поиск по товарам на onliner на примере поиска смартфона: ты вводишь в строку поиска "смартфон", он тебе выводит все смартфоны, которые у них вообще имеются. Затем ты вводишь название компании производителя: apple. Он тебе показывает все телефоны apple, которые есть в каталоге. Их, очевидно, меньше чем по запросу "смартфон". Задем ты вводишь модель 7s - тебе в выдачу попадает ещё меньше телефонов и т.д. 

Эта функция, по сути, работает так же. На вход подаём информацию из базы данных и набор параметров, а на выходе появляется отфильтрованная информация по переданным параметрам.
